+ pandas dataframe pdf의 'modifed_title' column에서 '' 값의 개수가 몇개인지 세는 것

In [ ]:
## '' 인 것 개수 세기
from collections import Counter

Counter(pdf['modifed_title'])['']

+ 리스트에서 1의 개수 세기

In [1]:
from collections import Counter
Counter([1,2,3,1,2,3,4,1,2,3,1,5,2,1,2,3,1])[1]

6