In [7]:
import pandas as pd
pdf = pd.DataFrame(data={'first_col':[1,2,3,1,2,3,4,5], 'second_col':[11,12,13,11,0,0,0,0]})
pd

### (1) pdf.duplicated(subset=['first_col'])
+ subset 안 넣으면, dataframe 전체 column에 대해서, 겹쳐야 겹치는 row로 판정
+ subset 넣으면, 설정한 모든 column들이 겹쳐야, 겹치는 row로 판정

In [8]:
print(sum(pdf.duplicated(subset=['first_col'])))
pdf.duplicated(subset=['first_col'])

3

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7    False
dtype: bool

In [9]:
pdf.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
dtype: bool

### (2) pdf.drop_duplicates(['first_col'], keep='first')
+ 중복의 기준이 되는 column 설정
+ keep
    + 중복되는 것 중 어떤 것 살릴지 설정 가능

In [10]:
pdf.drop_duplicates(['first_col'], keep='first')  # 처음 나오는 것 살리기

   first_col  second_col
0          1          11
1          2          12
2          3          13
6          4           0
7          5           0