## [1] 값 보기

### (1) .values

In [ ]:
import pandas as pd

a = pd.DataFrame({'col1':[1,2,3],'col2':[11,111,33]})
print(a.values)

print('-----')

for col1, col2 in a.values:
    print(col1, col2)

[[  1  11]
 [  2 111]
 [  3  33]]
-----
1 11
2 111
3 33

## [2] indexing

### (1) .loc 기본
+ index으로 접근
+ pandas_df.loc[:n] : n까지 indexing

In [ ]:
import pandas as pd

a = pd.DataFrame({'col1':['첫째행','둘째행','셋째행'],'col2':[1,2,3]}, index=(0,1,3))
a

  col1  col2
0  첫째행     1
1  둘째행     2
3  셋째행     3

In [ ]:
a.loc[:1]

  col1  col2
0  첫째행     1
1  둘째행     2

In [ ]:
a.loc[[1]] # 1개 row 접근할 때, df로 만들고 싶으면 [] 2개 이용

  col1  col2
1  둘째행     2

In [ ]:
a.loc[1]

col1    둘째행
col2      2
Name: 1, dtype: object

### (2) .iloc 기본
+ index가 아닌 순서로 접근
+ pandas_df.iloc[:n] -> n은 제외하고 indexing

In [ ]:
import pandas as pd
a = pd.DataFrame({'col1':['첫째행','둘째행','셋째행'],'col2':[1,2,3]}, index=(0,1,3))
a

  col1  col2
0  첫째행     1
1  둘째행     2
3  셋째행     3

In [ ]:
a.iloc[2] # index 접근이 아니라, (0부터 시작해서) 2번째 행에 접근하는 것

col1    셋째행
col2      3
Name: 3, dtype: object

In [ ]:
a.iloc[:3]

  col1  col2
0  첫째행     1
1  둘째행     2
3  셋째행     3

In [ ]:
a.iloc[:2]

  col1  col2
0  첫째행     1
1  둘째행     2

In [ ]:
a.iloc[:0]

Empty DataFrame
Columns: [col1, col2]
Index: []

In [ ]:
a.iloc[[1]]

  col1  col2
1  둘째행     2

In [ ]:
a.iloc[1]

col1    둘째행
col2      2
Name: 1, dtype: object

### (3) loc로 df value 바꾸기

In [3]:
import pandas as pd
a = pd.DataFrame({'col1':[1,2,3,4,5], 'col2':[100,200,300,400,500]})
# 1. 전체 column 바꾸기
a.loc[a['col1']>3] = '3보다 커서 바뀌었습니다.'
a

             col1            col2
0               1             100
1               2             200
2               3             300
3  3보다 커서 바뀌었습니다.  3보다 커서 바뀌었습니다.
4  3보다 커서 바뀌었습니다.  3보다 커서 바뀌었습니다.

In [5]:
# 2. 원하는 column 만 바꾸기
import pandas as pd
a = pd.DataFrame({'col1':[1,2,3,4,5], 'col2':[100,200,300,400,500]})
a.loc[a['col1']>3, 'col2'] = 'col1이 3보다 커서 바뀌었습니다.'
a

   col1                  col2
0     1                   100
1     2                   200
2     3                   300
3     4  col1이 3보다 커서 바뀌었습니다.
4     5  col1이 3보다 커서 바뀌었습니다.